module.exports.authService = require('./auth.service')
module.exports.tokenService = require('./token.service')
module.exports.userService = require('./user.service')
module.exports.cadresService = require('./cadres.service')
module.exports.newsService = require('./news.service')
module.exports.activityService = require('./activity.service')
