module.exports.authController = require('./auth.controller')
module.exports.cadresController = require('./cadres.controller')
module.exports.newsController = require('./news.controller')
module.exports.activityController = require('./activity.controller')
module.exports.userController = require('./user.controller')
